describe('Manual Optimisation Proofs', () => {
  it.todo('Properly implement automated tests');
  // <1> <2> OP_GREATERTHAN OP_NOT
  // <1> <2> OP_LESSTHANOREQUAL
  // OP_EQUALVERIFY

  // <2> <1> OP_GREATERTHAN OP_NOT
  // <2> <1> OP_LESSTHANOREQUAL
  // OP_EQUALVERIFY

  // <1> <1> OP_GREATERTHAN OP_NOT
  // <1> <1> OP_LESSTHANOREQUAL
  // OP_EQUALVERIFY




  // <1> <2> OP_LESSTHAN OP_NOT
  // <1> <2> OP_GREATERTHANOREQUAL
  // OP_EQUALVERIFY

  // <2> <1> OP_LESSTHAN OP_NOT
  // <2> <1> OP_GREATERTHANOREQUAL
  // OP_EQUALVERIFY

  // <1> <1> OP_LESSTHAN OP_NOT
  // <1> <1> OP_GREATERTHANOREQUAL
  // OP_EQUALVERIFY



  // <1> <2> OP_LESSTHANOREQUAL OP_NOT
  // <1> <2> OP_GREATERTHAN
  // OP_EQUALVERIFY

  // <2> <1> OP_LESSTHANOREQUAL OP_NOT
  // <2> <1> OP_GREATERTHAN
  // OP_EQUALVERIFY

  // <1> <1> OP_LESSTHANOREQUAL OP_NOT
  // <1> <1> OP_GREATERTHAN
  // OP_EQUALVERIFY



  // <1> <2> OP_GREATERTHANOREQUAL OP_NOT
  // <1> <2> OP_LESSTHAN
  // OP_EQUALVERIFY

  // <2> <1> OP_GREATERTHANOREQUAL OP_NOT
  // <2> <1> OP_LESSTHAN
  // OP_EQUALVERIFY

  // <1> <1> OP_GREATERTHANOREQUAL OP_NOT
  // <1> <1> OP_LESSTHAN
  // OP_EQUALVERIFY
});
