import { Script } from 'bitbox-sdk';

const spedn = 'OP_3 OP_PICK OP_1 OP_EQUAL OP_IF OP_10 OP_PICK OP_SIZE OP_NIP OP_4 OP_EQUALVERIFY '
  + 'OP_9 OP_PICK OP_SIZE OP_NIP 64 OP_EQUALVERIFY OP_7 OP_PICK OP_SIZE OP_NIP OP_8 '
  + 'OP_EQUALVERIFY OP_6 OP_PICK OP_SIZE OP_NIP OP_4 OP_EQUALVERIFY OP_5 OP_PICK OP_SIZE '
  + 'OP_NIP 20 OP_EQUALVERIFY OP_4 OP_PICK OP_SIZE OP_NIP OP_8 OP_EQUALVERIFY OP_10 OP_PICK '
  + 'OP_10 OP_PICK OP_CAT OP_9 OP_PICK OP_CAT OP_8 OP_PICK OP_CAT OP_7 OP_PICK OP_CAT OP_6 '
  + 'OP_PICK OP_CAT OP_5 OP_PICK OP_CAT OP_12 OP_PICK OP_14 OP_PICK OP_CHECKSIGVERIFY OP_12 '
  + 'OP_PICK OP_SIZE OP_1SUB OP_SPLIT OP_DROP OP_OVER OP_SHA256 OP_15 OP_PICK OP_CHECKDATASIGVERIFY '
  + 'e803 OP_9 OP_PICK OP_BIN2NUM OP_3 OP_PICK OP_SUB OP_OVER OP_SUB OP_8 OP_NUM2BIN OP_3 OP_PICK '
  + 'OP_8 OP_NUM2BIN 76 87 a9 14 17 19 88 ac 008d27 OP_CHECKSEQUENCEVERIFY OP_DROP 16 OP_PICK '
  + 'OP_BIN2NUM OP_2 OP_GREATERTHANOREQUAL OP_VERIFY 14 OP_PICK OP_3 OP_SPLIT OP_NIP OP_10 '
  + 'OP_PICK OP_5 OP_PICK OP_CAT OP_7 OP_PICK OP_CAT OP_6 OP_PICK OP_CAT OP_OVER OP_HASH160 '
  + 'OP_CAT OP_8 OP_PICK OP_CAT OP_10 OP_PICK OP_5 OP_PICK OP_CAT OP_10 OP_PICK OP_CAT OP_8 '
  + 'OP_PICK OP_CAT OP_7 OP_PICK OP_CAT 11 OP_PICK OP_CAT OP_4 OP_PICK OP_CAT OP_3 OP_PICK '
  + 'OP_CAT OP_2DUP OP_CAT OP_HASH256 15 OP_PICK OP_EQUAL OP_NIP OP_NIP OP_NIP OP_NIP OP_NIP '
  + 'OP_NIP OP_NIP OP_NIP OP_NIP OP_NIP OP_NIP OP_NIP OP_NIP OP_NIP OP_NIP OP_NIP OP_NIP OP_NIP '
  + 'OP_NIP OP_NIP OP_NIP OP_NIP OP_NIP OP_NIP OP_NIP OP_NIP OP_NIP OP_NIP OP_ELSE OP_3 '
  + 'OP_PICK OP_2 OP_EQUAL OP_IF OP_5 OP_PICK OP_HASH160 OP_2 OP_PICK OP_EQUALVERIFY OP_4 '
  + 'OP_PICK OP_6 OP_PICK OP_CHECKSIG OP_NIP OP_NIP OP_NIP OP_NIP OP_NIP OP_NIP OP_ELSE '
  + 'OP_0 OP_ENDIF OP_ENDIF';

const cashc023 = 'OP_3 OP_PICK OP_0 OP_NUMEQUAL OP_IF OP_6 OP_PICK OP_SIZE OP_NIP OP_4 OP_NUMEQUALVERIFY OP_7 '
  + 'OP_PICK OP_SIZE OP_NIP 64 OP_NUMEQUALVERIFY OP_9 OP_PICK OP_SIZE OP_NIP OP_8 OP_NUMEQUALVERIFY '
  + 'OP_10 OP_PICK OP_SIZE OP_NIP OP_4 OP_NUMEQUALVERIFY OP_11 OP_PICK OP_SIZE OP_NIP 20 OP_NUMEQUALVERIFY '
  + 'OP_12 OP_PICK OP_SIZE OP_NIP OP_8 OP_NUMEQUALVERIFY OP_6 OP_PICK OP_8 OP_ROLL OP_CAT OP_8 OP_PICK '
  + 'OP_CAT OP_9 OP_PICK OP_CAT OP_10 OP_ROLL OP_CAT OP_10 OP_PICK OP_CAT OP_11 OP_ROLL OP_CAT OP_6 OP_PICK '
  + 'OP_6 OP_PICK OP_CHECKSIGVERIFY OP_6 OP_ROLL OP_SIZE OP_1SUB OP_SPLIT OP_DROP OP_SWAP OP_SHA256 '
  + 'OP_6 OP_ROLL OP_CHECKDATASIGVERIFY e803 OP_7 OP_ROLL OP_BIN2NUM OP_4 OP_PICK OP_SUB OP_SWAP '
  + 'OP_SUB OP_8 OP_NUM2BIN OP_3 OP_ROLL OP_8 OP_NUM2BIN 76 87 a9 14 17 19 88 ac 008d27 '
  + 'OP_CHECKSEQUENCEVERIFY OP_DROP OP_13 OP_ROLL OP_BIN2NUM OP_2 OP_GREATERTHANOREQUAL OP_VERIFY '
  + 'OP_13 OP_ROLL OP_3 OP_SPLIT OP_NIP OP_10 OP_ROLL OP_5 OP_ROLL OP_CAT OP_6 OP_PICK OP_CAT OP_5 '
  + 'OP_PICK OP_CAT OP_SWAP OP_HASH160 OP_CAT OP_6 OP_ROLL OP_CAT OP_7 OP_ROLL OP_4 OP_ROLL OP_CAT '
  + 'OP_6 OP_ROLL OP_CAT OP_5 OP_ROLL OP_CAT OP_4 OP_ROLL OP_CAT OP_4 OP_ROLL OP_CAT OP_3 OP_ROLL '
  + 'OP_CAT OP_ROT OP_CAT OP_CAT OP_HASH256 OP_3 OP_ROLL OP_EQUAL OP_NIP OP_NIP OP_ELSE OP_3 OP_ROLL '
  + 'OP_1 OP_NUMEQUAL OP_IF OP_3 OP_PICK OP_HASH160 OP_ROT OP_EQUALVERIFY OP_2SWAP OP_CHECKSIG OP_NIP '
  + 'OP_NIP OP_ELSE OP_0 OP_ENDIF OP_ENDIF';

const cashc030 = 'OP_3 OP_PICK OP_0 OP_NUMEQUAL OP_IF OP_4 OP_PICK OP_4 OP_SPLIT 65 OP_SPLIT OP_NIP OP_SIZE '
  + '34 OP_SUB OP_SPLIT OP_8 OP_SPLIT OP_4 OP_SPLIT OP_NIP 20 OP_SPLIT OP_DROP OP_10 OP_ROLL '
  + 'OP_10 OP_ROLL OP_2DUP OP_SWAP OP_SIZE OP_1SUB OP_SPLIT OP_DROP OP_12 OP_ROLL OP_SHA256 '
  + 'OP_ROT OP_CHECKDATASIGVERIFY OP_CHECKSIGVERIFY 008d27 OP_CHECKSEQUENCEVERIFY OP_DROP '
  + 'OP_3 OP_ROLL OP_BIN2NUM OP_2 OP_GREATERTHANOREQUAL OP_VERIFY e803 OP_6 OP_PICK OP_8 '
  + 'OP_NUM2BIN OP_3 OP_ROLL OP_BIN2NUM OP_7 OP_ROLL OP_SUB OP_ROT OP_SUB OP_8 OP_NUM2BIN '
  + 'OP_SWAP 1976a914 OP_CAT OP_4 OP_ROLL OP_CAT 88ac OP_CAT OP_SWAP 17a914 OP_CAT OP_3 '
  + 'OP_ROLL OP_HASH160 OP_CAT 87 OP_CAT OP_CAT OP_HASH256 OP_EQUAL OP_NIP OP_NIP OP_ELSE '
  + 'OP_3 OP_ROLL OP_1 OP_NUMEQUAL OP_IF OP_3 OP_PICK OP_HASH160 OP_ROT OP_EQUALVERIFY '
  + 'OP_2SWAP OP_CHECKSIG OP_NIP OP_NIP OP_ELSE OP_0 OP_ENDIF OP_ENDIF';

console.log(`Spedn bytecode size: ${new Script().fromASM(spedn).byteLength}`);
console.log(`CashScript 0.2.3 bytecode size: ${new Script().fromASM(cashc023).byteLength}`);
console.log(`CashScript 0.3.0 bytecode size: ${new Script().fromASM(cashc030).byteLength}`);
